name: ci

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-versions: [10.x, 12.x, 14.x, 15.x]
        redis-tag: [5, 6]

    services:
      redis:
        image: redis:${{ matrix.redis-tag }}
        ports:
        - 6379:6379

    steps:
      - uses: actions/checkout@v2
      - name: use node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: install dependencies
        run: npm i
      - run: npm test
