name: ci

on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-versions: [10, 12, 14]
        redis-tag: [5, 6]
        services:
          redis:
            image: redis:${{ matrix.redis-tag }}
            ports:
              - 6379:6379
            steps:
              - uses: actions/checkout@v2
              - name: build and test
                uses: actions/setup-node@v2
                with:
                  node-version: ${{ matrix.node-version }}
                run: npm i && npm test
